name: schedulelink
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.0.0
  firebase_auth: ^6.0.0
  cloud_firestore: ^6.0.0
  intl: ^0.20.2
  table_calendar: ^3.2.0
  multi_select_flutter: ^4.1.3
  provider: ^6.1.5
  shared_preferences: ^2.5.3
  flutter_colorpicker: ^1.1.0
  pdf: ^3.11.3
  csv: ^6.0.0
  firebase_storage: ^13.0.0
  path_provider: ^2.1.5
  open_file: ^3.3.2
  url_launcher: ^6.3.2
  geolocator: ^12.0.0
  geocoding: ^3.0.0
  google_fonts: ^6.2.1
  google_maps_flutter: ^2.6.1
  timezone: ^0.9.4
  share_plus: ^7.2.2
  firebase_messaging: ^16.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  # --- NEW DEPENDENCY ADDED ---
  flutter_launcher_icons: ^0.13.1

# --- NEW CONFIGURATION ADDED ---
# This block configures the launcher icon generator.
flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/icon.png"
  adaptive_icon_background: "#FFFFFF" # Your signature turquoise color
  adaptive_icon_foreground: "assets/icon/icon_foreground.png" # Your logo with a transparent background

  web:
    generate: true
    image_path: "assets/icon/icon.png"
    background_color: "#FFFFFF"
    theme_color: "#4DB6AC"

flutter:
  uses-material-design: true

  assets:
    - assets/fonts/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700