// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjvBmMCanT-iDcls-Hglb599C4A6xNNE8',
    appId: '1:763851501486:web:c7f11b7cbbe4263a27223f',
    messagingSenderId: '763851501486',
    projectId: 'schedulelink-28446',
    authDomain: 'schedulelink-28446.firebaseapp.com',
    storageBucket: 'schedulelink-28446.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZAFvH2PzUVQ38FNnw_7DyegBaHf8CDgw',
    appId: '1:763851501486:android:f9ad52336596a43827223f',
    messagingSenderId: '763851501486',
    projectId: 'schedulelink-28446',
    storageBucket: 'schedulelink-28446.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARo1IYU1AYuhNEmZ1pQex1ist-iztXIhc',
    appId: '1:763851501486:ios:05872cfb9a5d339027223f',
    messagingSenderId: '763851501486',
    projectId: 'schedulelink-28446',
    storageBucket: 'schedulelink-28446.firebasestorage.app',
    iosBundleId: 'com.example.schedulelink',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARo1IYU1AYuhNEmZ1pQex1ist-iztXIhc',
    appId: '1:763851501486:ios:05872cfb9a5d339027223f',
    messagingSenderId: '763851501486',
    projectId: 'schedulelink-28446',
    storageBucket: 'schedulelink-28446.firebasestorage.app',
    iosBundleId: 'com.example.schedulelink',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjvBmMCanT-iDcls-Hglb599C4A6xNNE8',
    appId: '1:763851501486:web:cd37de51b65303ff27223f',
    messagingSenderId: '763851501486',
    projectId: 'schedulelink-28446',
    authDomain: 'schedulelink-28446.firebaseapp.com',
    storageBucket: 'schedulelink-28446.firebasestorage.app',
  );

}